### ISSUE TITLE
vue-ace-editor preview

### ISSUE THREAD

**Issue by vasyl-bilous** [chairuosen/vue-ace-editor-demo#3]
Hi! First of all thank's for your amazing job. I can't figure out how to preview my HTML code with CSS? Also, it will be cool if the example put in codepen or something like that. So I will be very grateful to you if you can help me with my issue.

**Comment by chairuosen** [comment]
You want 2 things.

1.  preview my HTML code. 
What is the code? The code you typed in the editor? This is not editor's business. 
Or the demo's code? THere's no need to run demo with custom css.

2. Online demo preview.
OK, This is not supported yet. Because codepen or others do not support webpack.If you wanna see what UI looks like. Here's a [project](http://editor.ruosen.io/). I built a codepen by vue-ace-editor.

**Comment by vasyl-bilous** [comment]
1. Yes,  I'm mean the code typing in the editor and after that, I can check it in preview (exactly HTML page looks in the browser). 
2. Thanks for the answer I get it, but unfortunately, I can't watch your demo because have in console message: " Failed to load resource: net::ERR_NAME_NOT_RESOLVED   http://cdn.code.baidu.com/libs.js?_=1553258290899" ((
P.S. I think that I'm supposed to do it with Iframe. Am I right?
